title: "Astro Pi: Mission Zero"
hero_image: images/banner.png
description: Prepare for Mission Zero
theme: navy # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 0, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: space
technologies: sense-hat, electronic-components, python
site_areas: programmes
hardware: sense-hat, electronic-components
software: python
version: 4
last_tested: 2017-09-01
steps: 
- title: Introduction
- title: What you will need
- title: What is an Astro Pi?
- title: Display a message
- title: Add some colour
- title: Display an image
- title: Measure the temperature
- title: Display the temperature
- title: Submit your entry
- title: "Challenge: more Astro Pi projects"
